//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 02:39:38 PM ICT 
//


package poc.rest.api.dto;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the poc.rest.api.dto package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: poc.rest.api.dto
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CandidateListModel }
     * 
     */
    public CandidateListModel createCandidateListModel() {
        return new CandidateListModel();
    }

    /**
     * Create an instance of {@link CandidateDataModel }
     * 
     */
    public CandidateDataModel createCandidateDataModel() {
        return new CandidateDataModel();
    }

    /**
     * Create an instance of {@link CandidateInputModel }
     * 
     */
    public CandidateInputModel createCandidateInputModel() {
        return new CandidateInputModel();
    }

    /**
     * Create an instance of {@link FeedbackInputModel }
     * 
     */
    public FeedbackInputModel createFeedbackInputModel() {
        return new FeedbackInputModel();
    }

    /**
     * Create an instance of {@link CandidateSearchModel }
     * 
     */
    public CandidateSearchModel createCandidateSearchModel() {
        return new CandidateSearchModel();
    }

    /**
     * Create an instance of {@link AttachtmentModel }
     * 
     */
    public AttachtmentModel createAttachtmentModel() {
        return new AttachtmentModel();
    }

    /**
     * Create an instance of {@link FeedbackModel }
     * 
     */
    public FeedbackModel createFeedbackModel() {
        return new FeedbackModel();
    }

}
