/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.zeus.hr.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Candidate service. Represents a row in the &quot;zhr_Candidate&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.zeus.hr.model.impl.CandidateModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.zeus.hr.model.impl.CandidateImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Candidate
 * @see com.zeus.hr.model.impl.CandidateImpl
 * @see com.zeus.hr.model.impl.CandidateModelImpl
 * @generated
 */
@ProviderType
public interface CandidateModel extends BaseModel<Candidate>, ShardedModel,
	StagedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a candidate model instance should use the {@link Candidate} interface instead.
	 */

	/**
	 * Returns the primary key of this candidate.
	 *
	 * @return the primary key of this candidate
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this candidate.
	 *
	 * @param primaryKey the primary key of this candidate
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this candidate.
	 *
	 * @return the uuid of this candidate
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this candidate.
	 *
	 * @param uuid the uuid of this candidate
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the candidate ID of this candidate.
	 *
	 * @return the candidate ID of this candidate
	 */
	public long getCandidateId();

	/**
	 * Sets the candidate ID of this candidate.
	 *
	 * @param candidateId the candidate ID of this candidate
	 */
	public void setCandidateId(long candidateId);

	/**
	 * Returns the company ID of this candidate.
	 *
	 * @return the company ID of this candidate
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this candidate.
	 *
	 * @param companyId the company ID of this candidate
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this candidate.
	 *
	 * @return the group ID of this candidate
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this candidate.
	 *
	 * @param groupId the group ID of this candidate
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the first name of this candidate.
	 *
	 * @return the first name of this candidate
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this candidate.
	 *
	 * @param firstName the first name of this candidate
	 */
	public void setFirstName(String firstName);

	/**
	 * Returns the last name of this candidate.
	 *
	 * @return the last name of this candidate
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this candidate.
	 *
	 * @param lastName the last name of this candidate
	 */
	public void setLastName(String lastName);

	/**
	 * Returns the date of birth of this candidate.
	 *
	 * @return the date of birth of this candidate
	 */
	public Date getDateOfBirth();

	/**
	 * Sets the date of birth of this candidate.
	 *
	 * @param dateOfBirth the date of birth of this candidate
	 */
	public void setDateOfBirth(Date dateOfBirth);

	/**
	 * Returns the mobile phone of this candidate.
	 *
	 * @return the mobile phone of this candidate
	 */
	@AutoEscape
	public String getMobilePhone();

	/**
	 * Sets the mobile phone of this candidate.
	 *
	 * @param mobilePhone the mobile phone of this candidate
	 */
	public void setMobilePhone(String mobilePhone);

	/**
	 * Returns the email of this candidate.
	 *
	 * @return the email of this candidate
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this candidate.
	 *
	 * @param email the email of this candidate
	 */
	public void setEmail(String email);

	/**
	 * Returns the city of this candidate.
	 *
	 * @return the city of this candidate
	 */
	public long getCity();

	/**
	 * Sets the city of this candidate.
	 *
	 * @param city the city of this candidate
	 */
	public void setCity(long city);

	/**
	 * Returns the applied for of this candidate.
	 *
	 * @return the applied for of this candidate
	 */
	@AutoEscape
	public String getAppliedFor();

	/**
	 * Sets the applied for of this candidate.
	 *
	 * @param appliedFor the applied for of this candidate
	 */
	public void setAppliedFor(String appliedFor);

	/**
	 * Returns the note of this candidate.
	 *
	 * @return the note of this candidate
	 */
	@AutoEscape
	public String getNote();

	/**
	 * Sets the note of this candidate.
	 *
	 * @param note the note of this candidate
	 */
	public void setNote(String note);

	/**
	 * Returns the skills of this candidate.
	 *
	 * @return the skills of this candidate
	 */
	@AutoEscape
	public String getSkills();

	/**
	 * Sets the skills of this candidate.
	 *
	 * @param skills the skills of this candidate
	 */
	public void setSkills(String skills);

	/**
	 * Returns the source of this candidate.
	 *
	 * @return the source of this candidate
	 */
	@AutoEscape
	public String getSource();

	/**
	 * Sets the source of this candidate.
	 *
	 * @param source the source of this candidate
	 */
	public void setSource(String source);

	/**
	 * Returns the internal ID of this candidate.
	 *
	 * @return the internal ID of this candidate
	 */
	@AutoEscape
	public String getInternalId();

	/**
	 * Sets the internal ID of this candidate.
	 *
	 * @param internalId the internal ID of this candidate
	 */
	public void setInternalId(String internalId);

	/**
	 * Returns the received date of this candidate.
	 *
	 * @return the received date of this candidate
	 */
	public Date getReceivedDate();

	/**
	 * Sets the received date of this candidate.
	 *
	 * @param receivedDate the received date of this candidate
	 */
	public void setReceivedDate(Date receivedDate);

	/**
	 * Returns the internal note of this candidate.
	 *
	 * @return the internal note of this candidate
	 */
	@AutoEscape
	public String getInternalNote();

	/**
	 * Sets the internal note of this candidate.
	 *
	 * @param internalNote the internal note of this candidate
	 */
	public void setInternalNote(String internalNote);

	/**
	 * Returns the internal details of this candidate.
	 *
	 * @return the internal details of this candidate
	 */
	@AutoEscape
	public String getInternalDetails();

	/**
	 * Sets the internal details of this candidate.
	 *
	 * @param internalDetails the internal details of this candidate
	 */
	public void setInternalDetails(String internalDetails);

	/**
	 * Returns the attachment of this candidate.
	 *
	 * @return the attachment of this candidate
	 */
	@AutoEscape
	public String getAttachment();

	/**
	 * Sets the attachment of this candidate.
	 *
	 * @param attachment the attachment of this candidate
	 */
	public void setAttachment(String attachment);

	/**
	 * Returns the rating of this candidate.
	 *
	 * @return the rating of this candidate
	 */
	public int getRating();

	/**
	 * Sets the rating of this candidate.
	 *
	 * @param rating the rating of this candidate
	 */
	public void setRating(int rating);

	/**
	 * Returns the create date of this candidate.
	 *
	 * @return the create date of this candidate
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this candidate.
	 *
	 * @param createDate the create date of this candidate
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this candidate.
	 *
	 * @return the modified date of this candidate
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this candidate.
	 *
	 * @param modifiedDate the modified date of this candidate
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the created user of this candidate.
	 *
	 * @return the created user of this candidate
	 */
	public long getCreatedUser();

	/**
	 * Sets the created user of this candidate.
	 *
	 * @param createdUser the created user of this candidate
	 */
	public void setCreatedUser(long createdUser);

	/**
	 * Returns the modified user of this candidate.
	 *
	 * @return the modified user of this candidate
	 */
	public long getModifiedUser();

	/**
	 * Sets the modified user of this candidate.
	 *
	 * @param modifiedUser the modified user of this candidate
	 */
	public void setModifiedUser(long modifiedUser);

	/**
	 * Returns the status of this candidate.
	 *
	 * @return the status of this candidate
	 */
	public int getStatus();

	/**
	 * Sets the status of this candidate.
	 *
	 * @param status the status of this candidate
	 */
	public void setStatus(int status);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Candidate candidate);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Candidate> toCacheModel();

	@Override
	public Candidate toEscapedModel();

	@Override
	public Candidate toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}